version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.15.1

jobs:
  init:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run: yarn
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "yarn.lock" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - node_modules
  test:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: yarn test
  build:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: yarn build

workflows:
  main:
    jobs:
      - init
      - test:
          requires:
            - init
      - build:
          requires:
            - init
