name: Build
on:
  push:
    branches-ignore:
    - 'master'
    - 'rc'
  pull_request:
    branches-ignore:
    - 'master'
    - 'rc'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn build
      env:
        CMS_BASE_URL: ${{ secrets.CMS_BASE_URL }}
        CMS_API_KEY: ${{ secrets.CMS_API_KEY }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    - name: E2E Test
      uses: cypress-io/github-action@v1.16.1
      with:
        start: yarn start
        wait-on: 'http://localhost:3000'
      env:
        CMS_BASE_URL: ${{ secrets.CMS_BASE_URL }}
        CMS_API_KEY: ${{ secrets.CMS_API_KEY }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
