name: Deploy RC
on:
  push:
    branches:
    - 'rc'
env:
  STAGE_ENV: rc
  CACHE_VERSION: v1
  CMS_BASE_URL: ${{ secrets.CMS_BASE_URL }}
  CMS_API_KEY: ${{ secrets.CMS_API_KEY }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  NETLIFY_FUNCTIONS_BASE_URL_PROD: ${{ secrets.NETLIFY_FUNCTIONS_BASE_URL_PROD }}
  GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
  GA_TRACKING_ID_RC: ${{ secrets.GA_TRACKING_ID_RC }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ env.CACHE_VERSION }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ env.CACHE_VERSION }}-node-
    - run: yarn
    - run: yarn build
    - name: E2E Test
      uses: cypress-io/github-action@v2
      with:
        start: yarn start
        wait-on: 'http://localhost:3000'
    - name: Upload E2E test videos
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: E2E Test Videos
        path: test/e2e/videos
    - run: npx netlify deploy --dir=./dist
    - name: Notify to Slack
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: success()
      with:
        text: Success Deploy
        attachments: |
          [
            {
              "color": "good",
              "fields": [
                {
                  "value": "Success deploy to rc"
                }
              ]
            }
          ]
    - name: Notify to Slack
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: failure()
      with:
        text: Success Deploy
        attachments: |
          [
            {
              "color": "good",
              "fields": [
                {
                  "value": "Failure deploy to rc"
                }
              ]
            }
          ]
