name: Deploy RC
on:
  push:
    branches:
    - 'rc'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn build
      env:
        STAGE_ENV: rc
        CMS_BASE_URL: ${{ secrets.CMS_BASE_URL }}
        CMS_API_KEY: ${{ secrets.CMS_API_KEY }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
    - name: E2E Test
      uses: cypress-io/github-action@v1.16.1
      with:
        start: yarn start
        wait-on: 'http://localhost:3000'
      env:
        CMS_BASE_URL: ${{ secrets.CMS_BASE_URL }}
        CMS_API_KEY: ${{ secrets.CMS_API_KEY }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    - name: Upload E2E test videos
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: E2E Test Videos
        path: test/e2e/videos
    - run: npx netlify-cli deploy --dir=./dist
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
