name: Test
on: [pull_request]
env:
  CACHE_VERSION: v1
  CMS_BASE_URL: ${{ secrets.CMS_BASE_URL }}
  CMS_API_KEY: ${{ secrets.CMS_API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ env.CACHE_VERSION }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ env.CACHE_VERSION }}-node-
    - run: yarn
    - run: yarn build
    - name: E2E Test
      uses: cypress-io/github-action@v2
      with:
        start: yarn start
        wait-on: 'http://localhost:3000'
    - name: Upload E2E test videos
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: E2E Test Videos
        path: test/e2e/videos
    - name: Notify to Slack
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: success()
      with:
        text: Success Test
        attachments: |
          [
            {
              "color": "good",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "fields": [
                {
                  "title": "Branch",
                  "value": "${{ github.head_ref }}"
                }
              ]
            }
          ]
    - name: Notify to Slack
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: failure()
      with:
        text: Failure Test
        attachments: |
          [
            {
              "color": "danger",
              "author_name": "${{ github.actor }}",
              "author_icon": "${{ github.event.sender.avatar_url }}",
              "fields": [
                {
                  "title": "Branch",
                  "value": "${{ github.head_ref }}"
                }
              ]
            }
          ]
