name: Test
on:
  push:
    branches-ignore:
    - 'master'
    - 'rc'
  pull_request:
    branches-ignore:
    - 'master'
    - 'rc'
env:
  CACHE_VERSION: v1
  CMS_BASE_URL: ${{ secrets.CMS_BASE_URL }}
  CMS_API_KEY: ${{ secrets.CMS_API_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ env.CACHE_VERSION }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ env.CACHE_VERSION }}-node-
    - run: yarn
    - run: yarn build
    - name: E2E Test
      uses: cypress-io/github-action@v1.16.1
      with:
        start: yarn start
        wait-on: 'http://localhost:3000'
    - name: Upload E2E test videos
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: E2E Test Videos
        path: test/e2e/videos
